# Generated by Django 4.0.10 on 2023-03-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_chef_address_chef_age_chef_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chef',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
