# Generated by Django 4.0.10 on 2023-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0004_alter_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='meal content'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='listofwarnings',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='banner image'),
        ),
        migrations.AlterField(
            model_name='listofwarnings',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='warning content'),
        ),
    ]
