# Generated by Django 4.0.10 on 2023-04-17 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_alter_category_banner_image_alter_category_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='meals', to='meal.tag'),
        ),
    ]
