# Generated by Django 4.0.10 on 2023-03-10 16:49

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Egypt', max_length=180, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='EG', max_length=2, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('chef', 'chef'), ('customer', 'customer'), ('guest', 'guest')], default='customer', max_length=20, verbose_name='User Type'),
        ),
    ]
