# Generated by Django 4.0.10 on 2023-05-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
