# Generated by Django 4.0.10 on 2023-05-02 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
