# Generated by Django 4.0.10 on 2023-05-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='status',
        ),
    ]
